name: BIG n BIT Build & Deploy
# github workflow on push

on:
  push:
    branches: [ "feature/*" ]

jobs:
  build-and-publish:
    name: build and publish bignbit
    runs-on: ubuntu-latest
    env:
      VCS_CREDENTIALS_ID: "github.jpl.nasa.gov_devops_pw"
      GHCR_CREDENTIALS_ID: "github.com_packages_write_PAT"
      ECC_NEXUS_CREDENTIALS_ID: "earthdata.nexus"
      ECC_NEXUS_HOST: "maven.earthdata.nasa.gov"

    steps:
      - uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          installer-parallel: true

      - name: Make BIGnBIT 
          run: |
            chmod +x /build-lambda-zip.sh
            ./build-lambda-zip.sh
          shell: bash

      - name: Upload
          uses: actions/upload-artifact@v3.1.0
          with:
            name: bignbit
            path: dist/lambda-package/

  test:
    runs-on: ubuntu-latest
    env:
      VCS_CREDENTIALS_ID: "github.jpl.nasa.gov_devops_pw"
      GHCR_CREDENTIALS_ID: "github.com_packages_write_PAT"
      ECC_NEXUS_CREDENTIALS_ID: "earthdata.nexus"
      ECC_NEXUS_HOST: "maven.earthdata.nasa.gov"

    steps:
      - uses: actions/checkout@v3

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          installer-parallel: true

      - name: Poetry update
        run: poetry update

